# Generated by Django 4.1.4 on 2022-12-18 19:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("surname", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=256, unique=True)),
                (
                    "phoneNo",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region="IN"
                    ),
                ),
                ("facebookUserName", models.CharField(max_length=256, unique=True)),
                ("image", models.ImageField(null=True, upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, unique=True)),
                ("pageCount", models.IntegerField(default=0)),
                ("releaseDate", models.DateField(auto_now=True)),
                ("authors", models.ManyToManyField(to="books.author")),
                (
                    "genre",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="books.genre"
                    ),
                ),
            ],
        ),
    ]
