# Generated by Django 4.1.4 on 2022-12-18 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="books.genre"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="author", unique_together={("name", "surname")},
        ),
    ]
